### ISSUE TITLE
VSE Transform Tools do not behave the same in 2.8 as in 2.79...

### ISSUE THREAD

**Issue by Anybid** [doakey3/VSE_Transform_Tools#11]
Hello,

seems like there are some issues with this addon:

When the cursor is not in the preview window, the T command does not work.

Also when using the addon in 2.79, the distortion of the image (or video) was instantly removed, when adding the transform modifier, this does not work anymore in 2.8.

Thank you very much for your help,
Ralph

**Comment by doakey3** [comment]
The T command seems to work ok for me. Are you using the most recent version of the addon with Blender 2.8? Are there any error messages? I'm not sure what you mean about image distortion being removed. Can you provide an example?

**Comment by nexxio** [comment]
I think I Know what Anybid is talking about and is not a problem of the add-on. In previous versions to 2.79 you could activate the T command with the cursor over the Video sequencer strips editor but from the 2.79 version on it was changed and you have to put the cursor over the image preview viewport and press the T key. 
The distortion that he says is that when you import an image in the sequencer it expands to fit the screen/render size and it distorts, in older versions of the add-on it used to remove this distortion (by resetting the scaling of the image) when you activate the T command but now it doesn't do it anymore, what I do is that after pressing the T key I press Alt+S  that shortcut resets the scale of the image and clear the distortion.

**Comment by Anybid** [comment]
Thank you very much nexxio, this is exactly what I ment.
The work around with the Alt-S short cut works, but unfortunately it makes the add-on less convenient for me to use...;(

**Comment by lpslp** [comment]
_in older versions of the add-on it used to remove this distortion (by resetting the scaling of the image) when you activate the T command but now it doesn't do it anymore_

previously pressed T once and got everything right away, but now:
1-after selecting the right stip i must go cursor from stip side to preview side pres T
2-press alt + S
3-press S because it not fit reseted pics right always!
4-go back to stip side
and repeat in circle....
and now imagine 100-150 stips - back then in 2.7 ajust click RMB on them and press T - now is nightmare...


just wondering, developers - is there really are technical restrictions in 2.8 that you limit functionality or you )devs) thinks that so is more useful?

**Comment by doakey3** [comment]
No need to push T anyways. Select your strip in the preview window by right clicking, then press Alt S. 

If Alt S is not working properly, please submit an issue report and provide an example video file that causes the issue.

**Comment by lpslp** [comment]
doakey3 - you right BUT - in 2.7 (script ver.1.0) when you press T picture no matter they bigger than render resulusion or smaller - they by pressing T make right scale and FIT to render resulution. In 2.8 (script ver.1.2.8) if picture smaller than render resolution - always there are need S...  

p.s.
i want to use 2.8 because it faster and have font selection feature - but because all what i did said - i cant use it...
